services:
  ymmo-db:
    env_file:
      - .env
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - db_network

  ymmo-api:
    env_file:
      - .env
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ymmo-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      JWT_ACCESS_SECRET_KEY: ${JWT_ACCESS_SECRET_KEY}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      S3_ENDPOINT: http://ymmo-rustfs:9000
      S3_ACCESSKEY: ${S3_ACCESS_USER_KEY}
      S3_SECRETKEY: ${S3_SECRET_USER_KEY}
    depends_on:
      ymmo-db:
        condition: service_healthy
      ymmo-rustfs:
        condition: service_started
    restart: unless-stopped
    networks:
      - db_network
      - storage_network

  ymmo-rustfs:
    env_file:
      - .env
    image: rustfs/rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ROOT_USER: ${RUSTFS_ROOT_USER}
      RUSTFS_ROOT_PASSWORD: ${RUSTFS_ROOT_PASSWORD}
    volumes:
      - rustfs_data:/data
    restart: unless-stopped
    networks:
      - storage_network

  ymmo-pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4:9.15.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      ymmo-db:
        condition: service_healthy
    profiles:
      - tools
    restart: unless-stopped
    networks:
      - db_network

volumes:
  postgres_data:
  rustfs_data:
  pgadmin_data:

networks:
  db_network:
    driver: bridge
  storage_network:
    driver: bridge